### ISSUE TITLE
[STORY] UI : JSON Box should be smaller or fit in the box

### ISSUE THREAD

**Issue by navyayy** [siglens/siglens#572] opened 2024-02-23 12:20 UTC
# Description
![image](https://github.com/siglens/siglens/assets/108896805/d782ef0b-bc85-4a67-b45a-10ae9e107d4c)

Here, the JSON box is too large that the contents are not visible, it should be smaller in size such that it should fit in the box.

**Comment by mematcha** [comment] 2024-03-26 14:44
Can I work on this?

**Comment by nbhavana** [comment] 2024-03-26 14:48
go ahead

**Comment by Spoorthikulkarni01** [comment] 2024-03-26 14:53
Can I work on this?

**Comment by nbhavana** [comment] 2024-03-26 14:55
> Can I work on this?

its already assigned to someone else

**Comment by kaushikMreddy293** [comment] 2024-03-28 14:01
If this has not been completed, can I work on this?

**Comment by nbhavana** [comment] 2024-03-28 14:04
The issue is still open. You can submit a PR  if you are interested.

**Closed** 2024-04-06 12:22 UTC
Labels: good first issue
