### ISSUE TITLE
[STORY] Ensure that the search endpoint contains all necessary properties and returns the correct status code.

### ISSUE THREAD

**Issue by venkateshamatam** [siglens/siglens#577] opened 2024-02-23 15:33 UTC
# Description
- Validate the search endpoint `/api/search` and `/api/search/ws` to have the required properties before executing the search and return the appropriate status code for every request.
- The request JSON for the logs search looks like this 
```
{
  "state": "query",
  "searchText": "* | http_status=404",
  "startEpoch": "now-1h",
  "endEpoch": "now",
  "indexName": "*",
  "from": 0,
  "queryLanguage": "Splunk QL"
}
```
# Testing
- Test that no existing search functionality is broken and that validation is implemented for both `/api/search` and `/api/search/ws` endpoints.
- Manually test the endpoint with positive and negative testcases and verify that the appropriate status code is returned

**Comment by AndrewHess** [comment] 2024-02-26 16:55
Yep, go for it!

P.S. this issue looks like a duplicate of https://github.com/siglens/siglens/issues/534 so you might want to look at that too

**Comment by ksankeerth** [comment] 2024-02-28 02:38
> Yep, go for it!
> 
> P.S. this issue looks like a duplicate of #534 so you might want to look at that too

I've sent a PR. Let me know if any code has to be changed.
Thanks

**Closed** 2024-02-29 18:36 UTC
Labels: good first issue
